config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  post '/homes/sample_user_first_sign_in', to: 'homes#sample_user_first'
  post '/homes/sample_user_second_sign_in', to: 'homes#sample_user_second'
  post '/homes/sample_pharmacy_sign_in', to: 'homes#sample_pharmacy'
  post '/homes/developer_sign_in', to: 'homes#developer'
  post '/homes/admin_sign_in', to: 'homes#admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, except: %i[new create] do
    resources :medicine_notebook_records do
      resources :prescription_details, except: %i[index show]
    end
  end
  devise_for :pharmacies, controllers: {
    registrations: 'pharmacies/registrations',
    sessions: 'pharmacies/sessions'
  }
  resources :pharmacies, except: %i[new create]
  resources :likes, only: %i[create destroy]
  resources :information_disclosures, only: %i[create destroy]
  resources :medicines, except: [:edit]
  resources :take_method_details, only: %i[index new create destroy]
end

app/models/take_method_detail.rb
class TakeMethodDetail < ApplicationRecord
  validates :style, length: { maximum: 20 }, presence: true
  has_many :take_medicine_relations

  def self.to_hash_for_choices
    hash = {}
    self.pluck(:style).zip(self.pluck(:id)) do |style, index|
      hash[style] = index
    end
    hash
  end
end

app/controllers/take_method_details_controller.rb
class TakeMethodDetailsController < ApplicationController
  def index
    @take_method_details = TakeMethodDetail.all
  end
  
  def new
    @take_method_detail = TakeMethodDetail.new
  end
  
  def create
    @take_method_detail = TakeMethodDetail.new(take_method_detail_params)
    if @take_method_detail.save
      flash[:notice] = I18n.t('message.take_method_detail.create_success')
      redirect_to take_method_details_path
    else
      flash.now[:notice] = I18n.t('message.take_method_detail.create_failure')
      render :new
    end
  end

  def destroy
    @take_method_detail = TakeMethodDetail(params[:id])
    @take_method_detail.destroy
    flash[:notice] = I18n.t('message.take_method_detail.destroy_failure')
    redirect_to take_method_details_path
  end

  private

  def take_method_detail_params
    params.require(:take_method_detail).permit(:style)
  end
end

app/views/take_method_details/index.html.erb
<h1><%= t('activerecord.title.take_method_detail.index') %></h1>
<%= link_to t('button.take_method_detail_new'), new_take_method_detail_path %>
<hr>

<% @take_method_details.each_with_index do |method, index| %>
  <%= "#{index}: #{method.style}" %> <%= link_to t('button.take_method_detail_destroy') %><br>
<% end %>

app/views/take_method_details/new.html.erb
<h1><%= t('activerecord.title.take_method_detail.new') %></h1>

<% if @take_method_detail.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@take_method_detail.errors.count, t('errors.messages.can_not_create_because_have_any_error')) %></h2>
    <ul>
      <% @take_method_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @take_method_detail, local: true, url: create_or_update_root) do |f| %>
  <div>
    <%= f.label :style %>
    <%= f.text_field :style %>
  </div>

  <%= f.submit action_name_button %>
<% end %>

<%= link_to t('button.take_method_detail_index'), take_method_details_path %>