config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  post '/homes/sample_user_first_sign_in', to: 'homes#sample_user_first'
  post '/homes/sample_user_second_sign_in', to: 'homes#sample_user_second'
  post '/homes/sample_pharmacy_sign_in', to: 'homes#sample_pharmacy'
  post '/homes/developer_sign_in', to: 'homes#developer'
  post '/homes/admin_sign_in', to: 'homes#admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, except: %i[new create] do
    resources :medicine_notebook_records do
      resources :prescription_details, except: %i[index show]
    end
  end
  devise_for :pharmacies, controllers: {
    registrations: 'pharmacies/registrations',
    sessions: 'pharmacies/sessions'
  }
  resources :pharmacies, except: %i[new create]
  resources :likes, only: %i[create destroy]
  resources :information_disclosures, only: %i[create destroy]
  resources :medicines, except: [:edit]
  resources :take_method_details, only: %i[index new create destroy]
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :user
  has_many :medicine_record_relations
  validates :standard, :unit, presence: true
  validates :name, length: { maximum: 50 }, presence: true
  enum unit: { mg: 0, μg: 1 }
  enum permission: { permit: true, unpermit: false }

  def self.authority_category(current_user)
    case current_user.role
    when "master"
      self.all
    when "developer"
      self.where(user_id: current_user.id)
    end
  end

  def self.choices
    hash = {}
    permit_medicines = Medicine.where(permission: "permit")
    permit_medicines.pluck(:id, :name, :standard, :unit).each do | id, name, standard, unit |
      hash["#{name}#{standard}#{unit}"] = id
    end
    hash
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :not_pharmacy
  before_action :developer_privileges
  before_action :master_privileges, only: %i[update destroy]
  before_action :set_medicine, only: %i[show update destroy]

  def index
    @medicines = Medicine.authority_category(current_user)
  end

  def new
    @medicine = Medicine.new
  end

  def create
    @medicine = Medicine.new(medicine_params)
    @medicine.user_id = current_user.id
    if @medicine.save
      flash[:notice] = I18n.t('message.medicine.create_success')
      redirect_to medicines_path
    else
      flash[:notice] = I18n.t('message.medicine.create_failure')
      render :new
    end
  end

  def show
  end

  def update
    @medicine.update(permission: "permit")
    flash[:notice] = I18n.t('message.medicine.update_success')
    redirect_to @medicine
  end

  def destroy
    medicine_name = @medicine.name
    @medicine.destroy
    flash[:notice] = I18n.t('message.medicine.destroy_success', medicine_name: medicine_name )
    redirect_to medicines_path
  end

  private

  def not_pharmacy
    if pharmacy_signed_in?
      flash[:alert] = I18n.t('message.medicine.special_authority')
      redirect_to root_path
    end
  end

  def developer_privileges
    unless current_user.role == "master" || current_user.role == "developer"
      flash[:alert] = I18n.t('message.medicine.special_authority')
      redirect_to root_path
    end
  end

  def master_privileges
    if current_user.role != "master"
      flash[:alert] = I18n.t('message.medicine.only_admin')
      redirect_to root_path
    end
  end

  def set_medicine
    @medicine = Medicine.find(params[:id])
  end

  def medicine_params
    params.require(:medicine).permit(:name, :standard, :unit, :permission)
  end
end

app/views/medicines/_button.html.erb
<%= link_to t('button.medicine_update'), medicine_path(medicine), method: :patch, data: { confirm: t('message.medicine.update_confirm') } %><br>
<%= link_to t('button.medicine_destroy'), medicine_path(medicine), method: :delete, data: { confirm: t('message.medicine.destroy_confirm') } %><br>

app/views/medicines/index.html.erb
<h1><%= t('activerecord.title.medicine.index') %></h1>
<%= link_to t('button.medicine_new'), new_medicine_path %>
<hr>

<% @medicines.each do |medicine| %>
  <div>
    <%= link_to "#{medicine.name} #{medicine.standard}#{medicine.unit}", medicine_path(medicine) %><br>
    <%= only_master_view_in_medicines_index(current_user.role,medicine.user.name) %><br>
    <%= t('activerecord.attributes.medicine.permission') %> <%= medicine.permission_i18n %><br>
  </div>
  <hr>
<% end %>

app/views/medicines/new.html.erb
<h1><%= t('activerecord.title.medicine.new') %></h1>

<% if @medicine.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@medicine.errors.count, t('errors.messages.can_not_create_because_have_any_error')) %></h2>
    <ul>
      <% @medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @medicine, local: true, url: create_or_update_root) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :standard %>
    <%= f.text_field :standard %>
  </div>

  <div>
    <%= f.label :unit %>
    <%= f.select :unit, Medicine.units_i18n %>
  </div>

  <%= f.submit action_name_button %>
<% end %>

<%= link_to t('button.medicine_index'), medicines_path %>

app/views/medicines/show.html.erb
<h1><%= t('activerecord.title.medicine.show') %></h1>

<%= t('activerecord.attributes.medicine.name') %> <%= @medicine.name %><br>
<%= t('activerecord.attributes.medicine.standard') %> <%= @medicine.standard %><br>
<%= t('activerecord.attributes.medicine.unit') %> <%= @medicine.unit %><br>
<%= t('activerecord.attributes.medicine.permission') %> <%= @medicine.permission_i18n %><br>
<%= t('activerecord.attributes.user.registered_person') %> <%= @medicine.user.name %><br>

<%= link_to t('button.medicine_index'), medicines_path %>
<br>
<%= pharmacy_button_in_medicine_show(current_user,@medicine) %>