config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  post '/homes/sample_user_first_sign_in', to: 'homes#sample_user_first'
  post '/homes/sample_user_second_sign_in', to: 'homes#sample_user_second'
  post '/homes/sample_pharmacy_sign_in', to: 'homes#sample_pharmacy'
  post '/homes/developer_sign_in', to: 'homes#developer'
  post '/homes/admin_sign_in', to: 'homes#admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, except: %i[new create] do
    resources :medicine_notebook_records do
      resources :prescription_details, except: %i[index show]
    end
  end
  devise_for :pharmacies, controllers: {
    registrations: 'pharmacies/registrations',
    sessions: 'pharmacies/sessions'
  }
  resources :pharmacies, except: %i[new create]
  resources :likes, only: %i[create destroy]
  resources :information_disclosures, only: %i[create destroy]
  resources :medicines, except: [:edit]
  resources :take_method_details, only: %i[index new create destroy]
end

app/views/shared/_current_user_button_in_users_show.erb
<br>
<%= link_to t('button.medicine_notebook_record_index'), user_medicine_notebook_records_path(user) %>

app/views/shared/_mail.html.erb
<p><%= t('devise.mailer.reset_password_instructions.greeting', recipient: resource.name) %></p>

<p><%= t('devise.mailer.reset_password_instructions.instruction') %></p>

<p><%= link_to t('devise.mailer.reset_password_instructions.action'), edit_password_url(resource, reset_password_token: token) %></p>

<p><%= t('devise.mailer.reset_password_instructions.instruction_2') %></p>
<p><%= t('devise.mailer.reset_password_instructions.instruction_3') %></p>

app/views/shared/_notice_or_alert_message.html.erb
<% if notice.present? %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_notification.html.erb
<h2><%= t('activerecord.title.medicine_notebook_record.notification') %></h2>

<%= t('activerecord.attributes.user.side_effect') %>:<%= user.side_effect %><br>
<%= t('activerecord.attributes.user.allergy') %>:<%= user.allergy %><br>
<%= t('activerecord.attributes.user.sick') %>:<%= user.sick %><br>
<%= t('activerecord.attributes.user.operation') %>:<%= user.operation %><br>
<%= t('activerecord.attributes.user.note') %>:<%= user.note %><br>

app/views/shared/_pharmacy_button_in_medicine_notebook_records_index.html.erb
<%= link_to t('button.medicine_notebook_record_create'), new_user_medicine_notebook_record_path(@user) %>
<br>

app/views/shared/_pharmacy_button_in_medicine_notebook_records_show.html.erb
<%= link_to t('button.prescription_detail_new'), new_user_medicine_notebook_record_prescription_detail_path(user,medicine_notebook_record) %><br>
<%= link_to t('helpers.submit.update'), edit_user_medicine_notebook_record_path(user,medicine_notebook_record) %><br>
<%= link_to t('helpers.submit.destroy'), user_medicine_notebook_record_path(user,medicine_notebook_record), method: :delete, data: { confirm: I18n.t('message.medicine_notebook_record.confirmation_of_destruction') } %><br>

app/views/shared/_pharmacy_button_in_users_show.erb
<%= link_to t('button.medicine_notebook_record_index'), user_medicine_notebook_records_path(user) %>
<br>
<%= link_to t('button.medicine_notebook_record_create'), new_user_medicine_notebook_record_path(user) %>

app/views/shared/_record_summary.html.erb
<%= t('activerecord.attributes.pharmacy.name') %>:<%= medicine_notebook_record.pharmacy.name %><br>
<%= t('activerecord.attributes.medicine_notebook_record.date_of_issue') %>:<%= l(medicine_notebook_record.date_of_issue, format: :long) %><br>
<%= t('activerecord.attributes.medicine_notebook_record.date_of_dispensing') %>:<%= l(medicine_notebook_record.date_of_dispensing, format: :long) %><br>
<%= t('activerecord.attributes.medicine_notebook_record.medical_institution_name') %>:<%= medicine_notebook_record.medical_institution_name %><br>
<%= t('activerecord.attributes.medicine_notebook_record.doctor_name') %>:<%= medicine_notebook_record.doctor_name %><br>
<%= t('activerecord.attributes.medicine_notebook_record.note') %>:<%= medicine_notebook_record.note %><br>

app/views/shared/_sample_login.html.erb
<%= sample_user_first_login %>
<%= sample_user_second_login %>
<%= sample_pharmacy_login %>
<%= developer_login %>
<%= admin_login %>

app/views/shared/_user_button_in_users_show.erb
<%= link_to I18n.t('button.user_edit'), edit_user_path(user) %>
<br>
<%= link_to I18n.t('button.destroy'), user, method: :delete, data: { confirm: I18n.t('devise.registrations.edit.are_you_sure') } %>