config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  post '/homes/sample_user_first_sign_in', to: 'homes#sample_user_first'
  post '/homes/sample_user_second_sign_in', to: 'homes#sample_user_second'
  post '/homes/sample_pharmacy_sign_in', to: 'homes#sample_pharmacy'
  post '/homes/developer_sign_in', to: 'homes#developer'
  post '/homes/admin_sign_in', to: 'homes#admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, except: %i[new create] do
    resources :medicine_notebook_records do
      resources :prescription_details, except: %i[index show]
    end
  end
  devise_for :pharmacies, controllers: {
    registrations: 'pharmacies/registrations',
    sessions: 'pharmacies/sessions'
  }
  resources :pharmacies, except: %i[new create]
  resources :likes, only: %i[create destroy]
  resources :information_disclosures, only: %i[create destroy]
  resources :medicines, except: [:edit]
  resources :take_method_details, only: %i[index new create destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if Rails.env == "development" %>
      <%= params %><br>
      <%= session.keys %><br>
    <% end %>

    <!-- header -->
      <header style="text-align: center; background-color: silver; height: 50px;">
        <nav class="navbar navbar-light bg-light">
          <%= link_to t('app.title'), root_path, class: "navbar-brand" %>
          <%= welcome_model %>
          <%= user_sign_in_or_sign_out_button %>
          <%= pharmacy_sign_in_or_sign_out_button %>
          <%= user_sign_up_or_show_button %>
          <%= pharmacy_sign_up_or_show_button %>
          <%= user_search_button %>
          <%= link_to t('activerecord.title.pharmacy.search'), pharmacies_path, class: "btn btn-primary" %>
          <%= developer_button %>
        </div>
      </header>
    <!-- header -->

    <!-- sample_login -->
      <div style="text-align: center; background-color: silver;">
        <%= render partial: "shared/sample_login" %>
      </div>
    <!-- sample_login -->
    
    <!-- alert_message -->
      <%= render "shared/notice_or_alert_message" %>
    <!-- alert_message -->

    <!-- main-content -->
      <%= yield %>
    <!-- main-content -->

    <!-- footer -->
      <footer style="background-color: purple; color: white; font-size: 2rem; width: 100%; height: 30px; position: fixed; bottom: 0;">
        <p>Copyright © 2021 Yoshinori Shimoda All Rights Reserved.</p>
      </fotter>
    <!-- footer -->
  </body>
</html>